Require Java 7
Java 6 doesn't have the Integer.compare method, so the code already
didn't run on Java 6. This commit will make the plugin crash with a
UnsupportedClassVersionError instead of a NoSuchMethodError on Java 6
servers.